### ISSUE TITLE
TWRP

### ISSUE THREAD

**Issue by KirChi123** [TBM13/Samsung-Camera-Experiments#2]
How to enable raw on A20e with TWRP?

**Comment by TBM13** [comment]
If you have Magisk, use the module provided in the Releases, it's way easier to install it.
Otherwise, replace the library located at` /vendor/lib/libexynoscamera3.so` with [this one](https://github.com/TBM13/Samsung-Camera-Experiments/blob/master/A20e/Module_A20e/system/vendor/lib/libexynoscamera3.so)

**Comment by KirChi123** [comment]
How to replace it with TWRP?

**Comment by TBM13** [comment]
Either through ADB or using TWRP's file manager.
